// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofile.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace NetGrpcSentryTest.Service {
  public static partial class TestService
  {
    static readonly string __ServiceName = "NetGrpcSentryTest.Service.TestService";

    static readonly grpc::Marshaller<global::NetGrpcSentryTest.Service.Request> __Marshaller_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NetGrpcSentryTest.Service.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NetGrpcSentryTest.Service.Response> __Marshaller_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NetGrpcSentryTest.Service.Response.Parser.ParseFrom);

    static readonly grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response> __Method_ThrowsRpc = new grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ThrowsRpc",
        __Marshaller_Request,
        __Marshaller_Response);

    static readonly grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response> __Method_ThrowsExcpetion = new grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ThrowsExcpetion",
        __Marshaller_Request,
        __Marshaller_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NetGrpcSentryTest.Service.ProtofileReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TestService</summary>
    public abstract partial class TestServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::NetGrpcSentryTest.Service.Response> ThrowsRpc(global::NetGrpcSentryTest.Service.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::NetGrpcSentryTest.Service.Response> ThrowsExcpetion(global::NetGrpcSentryTest.Service.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TestService</summary>
    public partial class TestServiceClient : grpc::ClientBase<TestServiceClient>
    {
      /// <summary>Creates a new client for TestService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TestServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TestService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TestServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TestServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TestServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::NetGrpcSentryTest.Service.Response ThrowsRpc(global::NetGrpcSentryTest.Service.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ThrowsRpc(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NetGrpcSentryTest.Service.Response ThrowsRpc(global::NetGrpcSentryTest.Service.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ThrowsRpc, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NetGrpcSentryTest.Service.Response> ThrowsRpcAsync(global::NetGrpcSentryTest.Service.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ThrowsRpcAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NetGrpcSentryTest.Service.Response> ThrowsRpcAsync(global::NetGrpcSentryTest.Service.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ThrowsRpc, null, options, request);
      }
      public virtual global::NetGrpcSentryTest.Service.Response ThrowsExcpetion(global::NetGrpcSentryTest.Service.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ThrowsExcpetion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NetGrpcSentryTest.Service.Response ThrowsExcpetion(global::NetGrpcSentryTest.Service.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ThrowsExcpetion, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NetGrpcSentryTest.Service.Response> ThrowsExcpetionAsync(global::NetGrpcSentryTest.Service.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ThrowsExcpetionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NetGrpcSentryTest.Service.Response> ThrowsExcpetionAsync(global::NetGrpcSentryTest.Service.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ThrowsExcpetion, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TestServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TestServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TestServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ThrowsRpc, serviceImpl.ThrowsRpc)
          .AddMethod(__Method_ThrowsExcpetion, serviceImpl.ThrowsExcpetion).Build();
    }

  }
}
#endregion
