// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofile.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace NetGrpcSentryTest.Service {
  public static partial class TestService
  {
    static readonly string __ServiceName = "NetGrpcSentryTest.Service.TestService";

    static readonly grpc::Marshaller<global::NetGrpcSentryTest.Service.Request> __Marshaller_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NetGrpcSentryTest.Service.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NetGrpcSentryTest.Service.Response> __Marshaller_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NetGrpcSentryTest.Service.Response.Parser.ParseFrom);

    static readonly grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response> __Method_Unary = new grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Unary",
        __Marshaller_Request,
        __Marshaller_Response);

    static readonly grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response> __Method_ServerStream = new grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ServerStream",
        __Marshaller_Request,
        __Marshaller_Response);

    static readonly grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response> __Method_ClientStream = new grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "ClientStream",
        __Marshaller_Request,
        __Marshaller_Response);

    static readonly grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response> __Method_DuplexStream = new grpc::Method<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "DuplexStream",
        __Marshaller_Request,
        __Marshaller_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NetGrpcSentryTest.Service.ProtofileReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TestService</summary>
    public abstract partial class TestServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::NetGrpcSentryTest.Service.Response> Unary(global::NetGrpcSentryTest.Service.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task ServerStream(global::NetGrpcSentryTest.Service.Request request, grpc::IServerStreamWriter<global::NetGrpcSentryTest.Service.Response> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::NetGrpcSentryTest.Service.Response> ClientStream(grpc::IAsyncStreamReader<global::NetGrpcSentryTest.Service.Request> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task DuplexStream(grpc::IAsyncStreamReader<global::NetGrpcSentryTest.Service.Request> requestStream, grpc::IServerStreamWriter<global::NetGrpcSentryTest.Service.Response> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TestService</summary>
    public partial class TestServiceClient : grpc::ClientBase<TestServiceClient>
    {
      /// <summary>Creates a new client for TestService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TestServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TestService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TestServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TestServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TestServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::NetGrpcSentryTest.Service.Response Unary(global::NetGrpcSentryTest.Service.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Unary(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NetGrpcSentryTest.Service.Response Unary(global::NetGrpcSentryTest.Service.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Unary, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NetGrpcSentryTest.Service.Response> UnaryAsync(global::NetGrpcSentryTest.Service.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UnaryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NetGrpcSentryTest.Service.Response> UnaryAsync(global::NetGrpcSentryTest.Service.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Unary, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::NetGrpcSentryTest.Service.Response> ServerStream(global::NetGrpcSentryTest.Service.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ServerStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::NetGrpcSentryTest.Service.Response> ServerStream(global::NetGrpcSentryTest.Service.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ServerStream, null, options, request);
      }
      public virtual grpc::AsyncClientStreamingCall<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response> ClientStream(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ClientStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response> ClientStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_ClientStream, null, options);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response> DuplexStream(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DuplexStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::NetGrpcSentryTest.Service.Request, global::NetGrpcSentryTest.Service.Response> DuplexStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_DuplexStream, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TestServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TestServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TestServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Unary, serviceImpl.Unary)
          .AddMethod(__Method_ServerStream, serviceImpl.ServerStream)
          .AddMethod(__Method_ClientStream, serviceImpl.ClientStream)
          .AddMethod(__Method_DuplexStream, serviceImpl.DuplexStream).Build();
    }

  }
}
#endregion
